spring.application.name=RailWise
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ticket_booking_db

logging.level.org.springframework.security=DEBUG

# Mail (can keep same for both if needed)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=a.aliurooz786@gmail.com
spring.mail.password=mbfp ihka mrev swfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true