spring.application.name=RailWise

spring.data.mongodb.uri=mongodb+srv://aaliurooz786:f4ZaMSHnfABfHJPK@railwise-cluster.ipkismk.mongodb.net/railwise?retryWrites=true&w=majority&appName=RailWise-Cluster

logging.level.org.springframework.security=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=a.aliurooz786@gmail.com
spring.mail.password=mbfp ihka mrev swfx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true